name: Deploy to AWS S3
on:
  push:
    branches:
      - main
env:
  PYTHON_VERSION: '3.13'
  AWS_REGION: 'us-east-1'
  PELICAN_SETTINGS: 'pelicanconf.py'
  SITEURL: 'https://tighov.link'
  FEED_DOMAIN: 'https://tighov.link'
  BUCKET_NAME: 'tighov.link'
  OUTPUT_PATH: 'output'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install requirements
        run: pip install --upgrade pip && pip install pipenv && pipenv install
      - name: Build Pelican site
        shell: python
        run: |
          import subprocess

          cmd = "pipenv run pelican"
          cmd += " --settings ${{ env.PELICAN_SETTINGS }}"
          cmd += " --extra-settings"
          cmd += """ SITEURL='"${{ env.SITEURL || steps.pages.outputs.base_url }}"'"""
          cmd += """ FEED_DOMAIN='"${{ env.FEED_DOMAIN || steps.pages.outputs.base_url }}"'"""
          cmd += " --output ${{ env.OUTPUT_PATH }}"
          cmd += " --theme-path theme"

          subprocess.run(cmd, shell=True, check=True)
      - name: Upload outputfolder 
        uses: actions/upload-artifact@master
        with:
          name: outputfolder
          path: ./${{ env.OUTPUT_PATH }}/
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@master
        with:
          name: outputfolder
          path: ./${{ env.OUTPUT_PATH }}/
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Copy files to S3 bucket
        run: |
          ls
          aws s3 sync ${{ env.OUTPUT_PATH }}/ s3://${{ env.BUCKET_NAME }}