name: Deploy to AWS S3
on:
  push:
    branches:
      - main
env:
  PYTHON_VERSION: '3.13'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install requirements
        run: pip install --upgrade pip && pip install pipenv && pipenv install
      - name: Activate virtual environment
        run: echo PATH=${GITHUB_WORKSPACE}/.venv/bin:$PATH >> $GITHUB_ENV
      - name: Build Pelican site
        shell: python
        run: |
          import subprocess

          cmd = "pelican"
          cmd += " --settings ${{ inputs.settings }}"
          cmd += " --extra-settings"
          cmd += """ SITEURL='"${{ inputs.siteurl || steps.pages.outputs.base_url }}"'"""
          cmd += """ FEED_DOMAIN='"${{ inputs.feed_domain || steps.pages.outputs.base_url }}"'"""
          cmd += " --output ${{ inputs.output-path }}"

          if "${{ inputs.theme }}":
              cmd += " --theme-path .theme"

          subprocess.run(cmd, shell=True, check=True)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3